version: '3'
services:

  # TODO two networks, one backend and one frontend

  frontend:
    container_name: whataretheodds-frontend
    build: ./frontend
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    volumes:
      - django-staticfiles:/usr/share/nginx/html/static

  backend:
    container_name: whataretheodds-backend
    build: ./backend
    env_file:
      - .env
    volumes:
      - django-staticfiles:/app/static

  postgres:
    container_name: whataretheodds-postgres
    image: postgres
    env_file:
      - .env

  redis:
    container_name: whataretheodds-redis
    image: redis

volumes:
  django-staticfiles:
